id: PC0081177
initial_creation_type: ocr
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA1KG982
  instance_id: http://purl.bdrc.io/resource/IE1KG982
  collection_id: http://purl.bdrc.io/resource/PR0ET009
  language_id: http://purl.bdrc.io/resource/LangBo
  title:
    bo:
    - གསོ་རིག་དཔྱད་རྩོམ་ཀུནྡ་དགྱེས་པའི་ཟླ་ཟེར།
  alt_title:
    zh-latn-pinyin-x-ndia:
    - xue yu yi yao xin tan
  author: http://purl.bdrc.io/resource/P1KG983
  publisher: UCB-OCR
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  volumes:
    0bcde7255c324505ab56ebe0e3fa4584:
      title: པོད ༡་གསོ་རིག་དཔྱད་རྩོམ་ཀུནྡ་དགྱེས་པའི་ཟླ་ཟེར
      volume_number: 1
      base_file: UT1KG982_I1KG1127_0000.txt
      reference: http://purl.bdrc.io/resource/VL3CEF5AB7A5AAFC83
      image_group: I1KG1127
      quality: Low
  reproductionOf:
  - http://purl.bdrc.io/resource/W1KG982
  - http://purl.bdrc.io/resource/MW1KG982
  ocr_software: Namsel
created_at: '2021-12-22T11:01:17.228779'
last_modified_at: '2021-12-22T11:01:17.228786'
statistics:
  total_words: 68769
  total_non_words: 10565
quality:
  non_words_ratio: 0.15
